# This is a generated file. Not intended for manual editing.
services:
  cleanarchitecture.api:
    build:
      context: "/home/tnt/Documentos/estudos/C#/Boilerplate"
      dockerfile: "CleanArchitecture.Api/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net10.0/CleanArchitecture.Api.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "cleanarchitecture.api:dev"
    ports: []
    volumes:
    - "/home/tnt/Documentos/estudos/C#/Boilerplate/CleanArchitecture.Api:/app:rw"
    - "/home/tnt/Documentos/estudos/C#/Boilerplate:/src:rw"
    - "/home/tnt/.nuget/packages:/home/app/.nuget/packages"
    working_dir: "/app"
